# Generated by Django 3.0.4 on 2020-08-25 15:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0003_homeworklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeworkfeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_id', models.IntegerField()),
                ('datetime', models.DateField()),
                ('file_name', models.FileField(upload_to='homework/hw_submission')),
                ('status', models.CharField(max_length=255)),
                ('feedback', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.RenameField(
            model_name='homeworklist',
            old_name='creator',
            new_name='creator_name',
        ),
        migrations.RenameField(
            model_name='homeworklist',
            old_name='id',
            new_name='hw_id',
        ),
        migrations.RemoveField(
            model_name='homeworklist',
            name='date',
        ),
        migrations.RemoveField(
            model_name='homeworklist',
            name='name',
        ),
        migrations.AddField(
            model_name='homeworklist',
            name='datetime',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='homeworklist',
            name='hw_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregister',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homeworklist',
            name='hw_desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homeworklist',
            name='hw_file',
            field=models.FileField(upload_to='homework/hw_files'),
        ),
        migrations.CreateModel(
            name='MyUserAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
