# Generated by Django 3.0.4 on 2020-08-26 01:10

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_auto_20200825_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkfeedback',
            old_name='file_name',
            new_name='hw_file',
        ),
        migrations.AddField(
            model_name='homeworkfeedback',
            name='hw_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeworkfeedback',
            name='student_notes',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeworkfeedback',
            name='datetime',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
