# Generated by Django 3.0.4 on 2020-08-26 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_auto_20200825_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkfeedback',
            name='hw_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.HomeworkList'),
        ),
    ]
