# Generated by Django 3.0.4 on 2020-08-26 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_auto_20200825_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkfeedback',
            name='id',
        ),
        migrations.AddField(
            model_name='homeworkfeedback',
            name='feedback_id',
            field=models.IntegerField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
